### PR TITLE
Exception handling

### LINKED ISSUE #12: Add exception handling for REST API
---
### Description

In this task, we need to add exception handling for REST API to provide human-readable messages for users

### Links to read
- [Exceptions in Spring Web](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-exceptionhandler)
- [Controller Advice in Spring Web](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-controller-advice)
- [@ControllerAdvice JavaDocs](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/ControllerAdvice.html)
- [Exception Handling in Spring MVC](https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc) 
  - (pay special attention to `Using @ControllerAdvice Classes`, `Errors and REST`, `What to Use When?` sections)
- [Error Handling for REST with Spring](https://www.baeldung.com/exception-handling-for-rest-with-spring)

### Definition of Done (DoD)
- [x] Added high-level exception (either `Exception` or `RuntimeException`) handler so we do not expose stack trace to users;
- [x] Added exception handler for custom exception (like `UserNotFoundException`);
- [x] Added exception handler for domain model's constraint violations;
- [x] Sonar's quality gates passed and all code smells are fixed;
- [x] Code review and PR merged

### PR DESCRIPTION
**Pull request by COCONUTmkII**
Created exception handling

### CODE REVIEW

File: src/main/java/by/itechart/api/exception/UserResponseEntityExceptionHandler.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+    @ResponseBody
+    @ExceptionHandler(UserNotFoundException.class)
+    @ResponseStatus(HttpStatus.BAD_REQUEST)
+    protected ExceptionInfo handleUserNotFoundException(UserNotFoundException ex) {
+        String bodyOfResponse = ex.getMessage();
+        return new ExceptionInfo(bodyOfResponse);
+    }
+
+    @Override
+    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatus status, WebRequest request) {
```
Comment (Dauren-Delmukhambetov) [inline src/main/java/by/itechart/api/exception/UserResponseEntityExceptionHandler.java:30]: Why do you return `Object` and not `ExceptionInfo` itself as in the handler above?

**Review by Dauren-Delmukhambetov — APPROVED** [review]

File: src/main/java/by/itechart/api/exception/UserResponseEntityExceptionHandler.java (hunk 1 above)
Comment (COCONUTmkII) [reply src/main/java/by/itechart/api/exception/UserResponseEntityExceptionHandler.java:30]: The problem is when I create a custom method to handle `MethodArgumentNotValidException` that will return our `ExceptionInfo` there will be an error about the ambiguity of `ExceptionHandler` because `MethodArgumentNotValidException` is already defined with `@ExceptionHandler` annotation in the `ResponseEntityExceptionHandler` class. 
Here are the details: https://stackoverflow.com/questions/51991992/getting-ambiguous-exceptionhandler-method-mapped-for-methodargumentnotvalidexce
