### PR TITLE
data validation

### LINKED ISSUE #11: Add data validation on REST API
---
### Description

In this task, we need to add data validation for inputs in creation and modification methods.

### Links to read

- [Java Bean Validation Basics by Baeldung](https://www.baeldung.com/javax-validation)
- [Chapter 3. Validation, Data Binding, and Type Conversion](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#validation)
  - [3.1. Validation by Using Spring’s Validator Interface](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#validator)
  - [ 3.2. Resolving Codes to Error Messages](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#validation-conversion)
  - [3.7. Java Bean Validation](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#validation-beanvalidation)
- [JSR-380 Bean Validation 2.0](https://jcp.org/aboutJava/communityprocess/final/jsr380/index.html) (no need to read the whole specification file, just quickly go through the document)
  - Chapter 8. Built-in Constraint definitions (pay attention to constraint annotations)
  
### Definition of Done (DoD)

- [x] Bean validation provider configured
- [x] Validator injected on service level
- [x] Domain object validated before saving
- [x] User gets feedback on domain objects validation (just as an exception for now)
- [x] Code review
- [x] PR merged

### PR DESCRIPTION
**Pull request by COCONUTmkII**
Created validation

### CODE REVIEW

File: src/main/java/by/itechart/api/configuration/util/annotation/Telephone.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package by.itechart.api.configuration.util.annotation;
```
Comment (Dauren-Delmukhambetov) [inline src/main/java/by/itechart/api/configuration/util/annotation/Telephone.java]: Why did you decide to place it in the `configuration` package?

File: src/main/java/by/itechart/api/configuration/util/validation/TelephoneValidator.java [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+
+import javax.validation.ConstraintValidator;
+import javax.validation.ConstraintValidatorContext;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+public class TelephoneValidator implements ConstraintValidator<Telephone, String> {
+    @Override
+    public boolean isValid(String value, ConstraintValidatorContext context) {
+        Pattern pattern = Pattern.compile("^[+{375}]*\\s[(][0-9]{2}[)]\\s[0-9]{3}[-][0-9]{2}[-][0-9]{2}");
```
Comment (Dauren-Delmukhambetov) [inline src/main/java/by/itechart/api/configuration/util/validation/TelephoneValidator.java]: Do we support only mobile numbers? What about international users?
Users from Russia, Kazakhstan, the USA, and China (and a lot of more countries) are crying right now because they won't be able to sign up in our app :wink:

File: src/main/java/by/itechart/api/entity/User.java [hunk 3]
```diff
@@ -16,8 +16,10 @@
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Long id;
 
+
```
Comment (Dauren-Delmukhambetov) [inline src/main/java/by/itechart/api/entity/User.java]: Just nitpicking: why did you add these empty lines?

**Review by Dauren-Delmukhambetov — APPROVED** [review]
Good implementation of custom validation constraint! :+1:

File: src/main/java/by/itechart/api/entity/User.java (hunk 3 above)
Comment (COCONUTmkII) [reply src/main/java/by/itechart/api/entity/User.java]: It was my intellij IDEA when I was pushing my code in repo :3 Their implementation of code refactoring before push is still not good =(

File: src/main/java/by/itechart/api/configuration/util/validation/TelephoneValidator.java (hunk 2 above)
Comment (COCONUTmkII) [reply src/main/java/by/itechart/api/configuration/util/validation/TelephoneValidator.java]: Alright, I will return the previous pattern :3

File: src/main/java/by/itechart/api/configuration/util/annotation/Telephone.java (hunk 1 above)
Comment (COCONUTmkII) [reply src/main/java/by/itechart/api/configuration/util/annotation/Telephone.java]: I misclicked I guess :)

**Review by Dauren-Delmukhambetov — APPROVED** [review]
